### ISSUE TITLE
6.2.2 Weighted Averages

### ISSUE THREAD

**Issue by nzjakemartin** [weisscharlesj/SciCompforChemists#1]
Thank you for this great resource!

I think there is a small error in the Weighted Averages section (pg 182) the equation is divided by 5 but I think this should be 9 (and in fact the python code uses 9 so I think the actual python code is correct).

Thanks again.

**Comment by weisscharlesj** [comment]
You are correct that the equation is a typo but the code is correct; thank
you for catching this. I'll fix it in the next version. I keep a list of
people who provided feedback and reported errors at the beginning of the
book. I'm happy to include you. I'll list you as nzjakemartin unless you
have a different preference.

Kind regards,
Charlie Weiss

**Comment by weisscharlesj** [comment]
Typo fixed in version 1.0.6b.
