### ISSUE TITLE
Incorrect element data in Chapter 10

### ISSUE THREAD

**Issue by avalanchian** [weisscharlesj/SciCompforChemists#2]
I'm not sure where the element data for chapter 10 came from, but Tl-Rn are incorrectly categorised as d-block elements. As I'm sure you know, they should be p-block elements. I wouldn't have noticed if the graph in the chapter didn't show a d-block gas (see attached graph from Chapter 10.3.5)

If you left it incorrect intentionally for demonstrative purposes, it may be worth leaving a note saying as much. Otherwise, if you like I can submit a PR and fix it up? 

![image](https://github.com/weisscharlesj/SciCompforChemists/assets/38004153/33245204-8e79-40ee-b710-27625e81ff5d)

**Comment by weisscharlesj** [comment]
Thank you for letting me know about this issue; I'll get this fixed in my
next update to the text. I plan to include you in my acknowledgements for
reporting this error, so if you have a preferred way of being listed,
please let me know.
